export declare const variableSources: {
    player: {
        key: number;
        index: 60;
    };
    npc: {
        key: number;
        index: 61;
    };
    client: {
        key: number;
        index: 62;
    };
    world: {
        key: number;
        index: 63;
    };
    region: {
        key: number;
        index: 64;
    };
    object: {
        key: number;
        index: 65;
    };
    clan: {
        key: number;
        index: 66;
    };
    clansettings: {
        key: number;
        index: 67;
    };
    playergroup: {
        key: number;
        index: 75;
    };
};
export declare const namedClientScriptOps: {
    pushint: number;
    pushlong: number;
    pushstring: number;
    pushlocalint: number;
    poplocalint: number;
    pushlocalstring: number;
    poplocalstring: number;
    pushlocallong: number;
    poplocallong: number;
    popdiscardint: number;
    popdiscardlong: number;
    popdiscardstring: number;
    joinstring: number;
    gosub: number;
    pushvar: number;
    popvar: number;
    pushvarbit: number;
    popvarbit: number;
    jump: number;
    branch_not: number;
    branch_eq: number;
    branch_lt: number;
    branch_gt: number;
    branch_lteq: number;
    branch_gteq: number;
    branch_eq_long: number;
    branch_not_long: number;
    branch_lt_long: number;
    branch_gt_long: number;
    branch_lteq_long: number;
    branch_gteq_long: number;
    switch: number;
    return: number;
    pushconst: number;
    tribyte1: number;
    tribyte2: number;
    shorting_or: number;
    shorting_and: number;
    plus: number;
    minus: number;
    intdiv: number;
    intmul: number;
    strcmp: number;
    strconcat: number;
    inttostring: number;
    enum_getvalue: number;
    struct_getparam: number;
    item_getparam: number;
    quest_getparam: number;
    npc_getparam: number;
    cc_getparam: number;
    mec_getparam: number;
    dbrow_getfield: number;
    dbrow_findnext: number;
    cc_setparam: number;
    db_find_with_count: number;
    lc_getparam: number;
    enum_getstring: number;
    enum_getreverseindex: number;
    enum_getreversecount: number;
    enum_hasoutput: number;
    define_array: number;
    pop_array: number;
    push_array: number;
    printmessage: number;
};
export declare const subtypes: {
    int: number;
    boolean: number;
    type_2: number;
    quest: number;
    questhelp: number;
    cursor: number;
    seq: number;
    colour: number;
    loc_shape: number;
    component: number;
    idkit: number;
    midi: number;
    npc_mode: number;
    namedobj: number;
    synth: number;
    type_15: number;
    area: number;
    stat: number;
    npc_stat: number;
    writeinv: number;
    mesh: number;
    maparea: number;
    coordgrid: number;
    graphic: number;
    chatphrase: number;
    fontmetrics: number;
    enum: number;
    type_27: number;
    jingle: number;
    chatcat: number;
    loc: number;
    model: number;
    npc: number;
    obj: number;
    player_uid: number;
    type_35: number;
    string: number;
    spotanim: number;
    npc_uid: number;
    inv: number;
    texture: number;
    category: number;
    char: number;
    laser: number;
    bas: number;
    type_45: number;
    collision_geometry: number;
    physics_model: number;
    physics_control_modifier: number;
    clanhash: number;
    coordfine: number;
    cutscene: number;
    itemcode: number;
    type_54: number;
    mapsceneicon: number;
    clanforumqfc: number;
    vorbis: number;
    verify_object: number;
    mapelement: number;
    categorytype: number;
    social_network: number;
    hitmark: number;
    package: number;
    particle_effector: number;
    type_65: number;
    particle_emitter: number;
    plogtype: number;
    unsigned_int: number;
    skybox: number;
    skydecor: number;
    hash64: number;
    inputtype: number;
    struct: number;
    dbrow: number;
    type_75: number;
    type_76: number;
    type_77: number;
    type_78: number;
    type_79: number;
    type_80: number;
    type_81: number;
    type_83: number;
    type_84: number;
    type_85: number;
    type_86: number;
    type_87: number;
    type_88: number;
    gwc_platform: number;
    type_90: number;
    type_91: number;
    type_92: number;
    type_93: number;
    bug_template: number;
    billing_auth_flag: number;
    account_feature_flag: number;
    interface: number;
    toplevelinterface: number;
    overlayinterface: number;
    clientinterface: number;
    movespeed: number;
    material: number;
    seqgroup: number;
    temp_hiscore: number;
    temp_hiscore_length_type: number;
    temp_hiscore_display_type: number;
    temp_hiscore_contribute_result: number;
    audiogroup: number;
    audiomixbuss: number;
    long: number;
    crm_channel: number;
    http_image: number;
    pop_up_display_behaviour: number;
    poll: number;
    type_115: number;
    type_116: number;
    pointlight: number;
    player_group: number;
    player_group_status: number;
    player_group_invite_result: number;
    player_group_modify_result: number;
    player_group_join_or_create_result: number;
    player_group_affinity_modify_result: number;
    player_group_delta_type: number;
    client_type: number;
    telemetry_interval: number;
    type_127: number;
    type_128: number;
    type_129: number;
    type_130: number;
    achievement: number;
    stylesheet: number;
    type_138: number;
    type_200: number;
    type_201: number;
    type_202: number;
    type_203: number;
    type_204: number;
    type_205: number;
    type_206: number;
    type_207: number;
    type_208: number;
    var_reference: number;
    unknown_int: number;
    unknown_long: number;
    unknown_string: number;
    scriptref: number;
    scriptsubref: number;
};
export interface SubCallable {
    scriptname: string;
    originalindex: number;
    returntype: StackList;
    argtype: StackList;
    localCounts: StackDiff;
}
export type PrimitiveType = "int" | "long" | "string";
type DependentType = "known" | "opin" | "opout" | "scriptargvar" | "scriptret" | "uuid";
export declare function dependencyGroup(deptype: DependentType, id: number): number;
export declare function dependencyIndex(subtype: PrimitiveType, index: number): number;
export declare function knownDependency(fulltype: number): number;
export declare function keyToPrimitive(key: number): PrimitiveType;
export declare function decomposeKey(key: number): readonly [DependentType, PrimitiveType, number, number];
export declare function debugKey(key: number): string | undefined;
export declare const typeuuids: {
    int: number;
    long: number;
    string: number;
};
export declare function getOpName(id: number): string;
export declare function longJsonToBigInt(tuple: [number, number]): bigint;
export declare function longBigIntToJson(long: bigint): [number, number];
export declare function subtypeToTs(subt: number): string;
export declare function tsToSubtype(tscode: string): any;
export declare function typeToPrimitive(typeint: number): PrimitiveType;
export declare function primitiveToUknownExact(stacktype: PrimitiveType): number;
export declare const knownClientScriptOpNames: Record<number, string>;
export declare const popDiscardOps: number[];
export declare const popLocalOps: number[];
export declare const pushLocalOps: number[];
export declare const pushOrPopLocalOps: number[];
export declare const branchInstructionsInt: number[];
export declare const branchInstructionsLong: number[];
export declare const branchInstructions: number[];
export declare const binaryOpSymbols: Map<number, string>;
export declare const int32MathOps: Set<number>;
export declare const binaryOpIds: Map<string, number>;
export declare const branchInstructionsOrJump: number[];
export declare const getParamOps: number[];
export declare const dynamicOps: number[];
export declare function makeop(opcode: number, imm?: number, imm_obj?: ClientScriptOp["imm_obj"]): {
    opcode: number;
    imm: number;
    imm_obj: string | number | [number, number] | {
        type: "switchvalues";
        value: SwitchJumpTable;
    } | {
        type: "jumplabel";
        value: ClientScriptOp;
    } | null;
};
export declare function makejump(label: ClientScriptOp): {
    opcode: number;
    imm: number;
    imm_obj: {
        type: "jumplabel";
        value: ClientScriptOp;
    };
};
export type ImmediateType = "byte" | "int" | "tribyte" | "switch" | "long" | "string";
export type SwitchJumpTable = {
    value: number;
    jump: number;
}[];
export type ClientScriptOp = {
    opcode: number;
    imm: number;
    imm_obj: string | number | [number, number] | {
        type: "switchvalues";
        value: SwitchJumpTable;
    } | {
        type: "jumplabel";
        value: ClientScriptOp;
    } | null;
    opname?: string;
};
export declare class StackConstants {
    values: StackConst[];
    constructor(v?: StackConst);
    applyInOut(other: StackInOut): void;
    popList(other: StackList, endoffset?: number): void;
    pushOne(other: StackConst | undefined): void;
    pushList(other: StackList, endoffset?: number): void;
    push(other: StackConstants): void;
    pop(): string | number | [number, number] | {
        type: "switchvalues";
        value: SwitchJumpTable;
    } | {
        type: "jumplabel";
        value: ClientScriptOp;
    };
}
export type StackConst = ClientScriptOp["imm_obj"];
export type StackType = PrimitiveType | "vararg";
export type StackTypeExt = StackType | StackDiff;
export declare class StackList {
    values: StackTypeExt[];
    constructor(values?: StackTypeExt[]);
    pushone(type: StackType): void;
    int(): void;
    long(): void;
    string(): void;
    isEmpty(): boolean;
    total(endoffset?: number): number;
    tryShift(n: number): boolean;
    hasSimple(other: StackList): boolean;
    pop(list: StackList, limit?: number): void;
    tryPopReverse(list: StackList, limit?: number): number;
    tryPopUnordered(otherval: StackDiff): boolean;
    tryPopSingle(otherval: StackType): boolean;
    tryPop(list: StackList, limit?: number): number;
    push(list: StackList): void;
    clone(): StackList;
    toString(): string;
    toFunctionBindString(): string;
    toTypeScriptVarlist(withnames: boolean, withtypes: boolean, exacttype?: ExactStack | null): string;
    toTypeScriptReturnType(exacttype?: ExactStack | null): string;
    toJson(): (StackDiff | StackType)[];
    static fromJson(v: ReturnType<StackList["toJson"]>): StackList;
    getStackdiff(): StackDiff;
    toStackDiff(): StackDiff;
    toLooseSubtypes(): number[];
}
export declare class ExactStack {
    int: number[];
    long: number[];
    string: number[];
    all(): number[];
    static fromList(types: number[]): ExactStack;
    static fromJson(json: ReturnType<ExactStack['toJson']>): ExactStack;
    toJson(): this;
}
export declare class StackInOut {
    in: StackList;
    out: StackList;
    exactin: ExactStack | null;
    exactout: ExactStack | null;
    constout: StackConst;
    initializedin: boolean;
    initializedout: boolean;
    initializedthrough: boolean;
    constructor(inlist?: StackList, outlist?: StackList);
    static fromExact(inlist: number[], outlist: number[]): StackInOut;
    getBottomOverlap(): number;
    totalChange(): number;
    getCode(): string;
    toString(): string;
    toJson(): {
        in: (StackDiff | StackType)[];
        out: (StackDiff | StackType)[];
        initializedthrough: boolean;
        exactin: ExactStack | undefined;
        exactout: ExactStack | undefined;
    };
    static fromJson(json: ReturnType<StackInOut["toJson"]>): StackInOut;
}
export declare class StackDiff {
    int: number;
    long: number;
    string: number;
    vararg: number;
    static fromJson(json: ReturnType<StackDiff["toJson"]> | undefined | null): StackDiff | null;
    toJson(): this;
    constructor(int?: number, long?: number, string?: number, vararg?: number);
    sub(other: StackDiff): this;
    add(other: StackDiff): this;
    min(other: StackDiff): void;
    max(other: StackDiff): void;
    mult(n: number): this;
    intdiv(n: number): this;
    lteq(other: StackDiff): boolean;
    equals(other: StackDiff): boolean;
    isEmpty(): boolean;
    isNonNegative(): boolean;
    toString(): string;
    total(): number;
    clone(): StackDiff;
    isMonoType(): PrimitiveType | "multi";
    getSingle(stack: StackType): number;
    setSingle(stack: StackType, value: number): void;
    getArglist(): StackList;
    toFunctionBindString(): string;
    toTypeScriptVarlist(nameoffset: StackDiff, withnames: boolean, withtypes: boolean, exacttype?: ExactStack | null): string;
}
export {};
