import { clientscript } from "../../generated/clientscript";
import { ClientscriptObfuscation } from "./callibrator";
import { ClientScriptOp, StackDiff, StackList, SwitchJumpTable } from "./definitions";
import { CS2Api, UiRenderContext } from "../scripts/renderrsinterface";
type ScriptScope = {
    scriptid: number;
    index: number;
    ops: ClientScriptOp[];
    switches: SwitchJumpTable[];
    localints: number[];
    locallongs: bigint[];
    localstrings: string[];
};
export declare class ClientScriptInterpreter {
    intstack: number[];
    longstack: bigint[];
    stringstack: string[];
    scopeStack: ScriptScope[];
    calli: ClientscriptObfuscation;
    mockscripts: Map<number, (string | number | bigint)[]>;
    scope: ScriptScope | null;
    activecompid: number;
    clientcomps: (CS2Api | undefined)[];
    stalled: Promise<boolean> | void;
    uictx: UiRenderContext | null;
    constructor(calli: ClientscriptObfuscation, uictx?: UiRenderContext | null);
    reset(): void;
    popComponent(): CS2Api;
    getClientComp(imm: number): CS2Api;
    getComponent(compid: number): CS2Api;
    callscriptid(id: number): Promise<void>;
    runToEnd(): Promise<void>;
    callscript(script: clientscript, scriptid: number): void;
    log(text: string): void;
    pushStackdiff(diff: StackDiff): void;
    popStacklist(list: StackList): void;
    popvararg(): void;
    popStackdiff(diff: StackDiff): void;
    popdeep(depth: number): number;
    popdeeplong(depth: number): bigint;
    popdeepstr(depth: number): string;
    popint(): number;
    poplong(): bigint;
    popstring(): string;
    pushlist(list: (number | bigint | string)[]): void;
    pushint(v: number): void;
    pushlong(v: bigint): void;
    pushstring(v: string): void;
    next(): boolean | Promise<boolean>;
    dump(): void;
}
export {};
