export declare const cacheMajors: {
    readonly framemaps: 1;
    readonly config: 2;
    readonly interfaces: 3;
    readonly mapsquares: 5;
    readonly oldmodels: 7;
    readonly sprites: 8;
    readonly clientscript: 12;
    readonly fontmetricsOld: 13;
    readonly sounds: 14;
    readonly objects: 16;
    readonly enums: 17;
    readonly npcs: 18;
    readonly items: 19;
    readonly sequences: 20;
    readonly spotanims: 21;
    readonly structs: 22;
    readonly quickchat: 24;
    readonly materials: 26;
    readonly particles: 27;
    readonly worldmap: 23;
    readonly music: 40;
    readonly models: 47;
    readonly frames: 48;
    readonly texturesOldPng: 9;
    readonly texturesOldCompoundPng: 37;
    readonly textures2015Png: 43;
    readonly textures2015CompoundPng: 44;
    readonly textures2015Dds: 45;
    readonly textures2015CompoundPngMips: 46;
    readonly textures2015CompoundDds: 50;
    readonly textures2015PngMips: 51;
    readonly texturesDds: 52;
    readonly texturesPng: 53;
    readonly texturesBmp: 54;
    readonly texturesKtx: 55;
    readonly skeletalAnims: 56;
    readonly achievements: 57;
    readonly fontmetrics: 58;
    readonly vectorfonts: 59;
    readonly cutscenes: 66;
    readonly index: 255;
};
export declare const latestBuildNumber = 940;
export declare const cacheMapFiles: {
    readonly locations: 0;
    readonly squares: 3;
    readonly squaresWater: 4;
    readonly square_nxt: 5;
    readonly env: 6;
};
export declare const cacheConfigPages: {
    readonly mapunderlays: 1;
    readonly identityKit: 3;
    readonly mapoverlays: 4;
    readonly params: 11;
    readonly environments: 29;
    readonly animgroups: 32;
    readonly mapscenes: 34;
    readonly maplabels: 36;
    readonly dbtables: 40;
    readonly dbrows: 41;
    readonly varplayer: 60;
    readonly varnpc: 61;
    readonly varclient: 62;
    readonly varworld: 63;
    readonly varregion: 64;
    readonly varobject: 65;
    readonly varclan: 66;
    readonly varclansettings: 67;
    readonly varcampaign: 68;
    readonly varplayergroup: 75;
    readonly varbits: 69;
    readonly locs_old: 6;
    readonly npcs_old: 9;
    readonly items_old: 10;
    readonly spotanim_old: 13;
};
export declare const lastLegacyBuildnr = 377;
export declare const lastClassicBuildnr = 235;
