import * as opcode_reader from "./opcode_reader";
import type { CacheFileSource } from "./cache";
export declare class FileParser<T> {
    parser: opcode_reader.ChunkParser;
    originalSource: string;
    totaltime: number;
    static fromJson<T>(jsonObject: string): FileParser<T>;
    constructor(opcodeobj: unknown, originalSource?: string);
    readInternal(state: opcode_reader.DecodeState): any;
    read(buffer: Buffer, source: CacheFileSource, args?: Record<string, any>): T;
    write(obj: T, args?: Record<string, any>): Buffer<ArrayBufferLike>;
}
export declare const parse: {
    cacheIndex: FileParser<import("../generated/cacheindex").cacheindex>;
    npc: FileParser<import("../generated/npcs").npcs>;
    item: FileParser<import("../generated/items").items>;
    object: FileParser<import("../generated/objects").objects>;
    achievement: FileParser<import("../generated/achievements").achievements>;
    mapsquareTiles: FileParser<import("../generated/mapsquare_tiles").mapsquare_tiles>;
    mapsquareTilesNxt: FileParser<import("../generated/mapsquare_tiles_nxt").mapsquare_tiles_nxt>;
    mapsquareWaterTiles: FileParser<import("../generated/mapsquare_watertiles").mapsquare_watertiles>;
    mapsquareUnderlays: FileParser<import("../generated/mapsquare_underlays").mapsquare_underlays>;
    mapsquareOverlays: FileParser<import("../generated/mapsquare_overlays").mapsquare_overlays>;
    mapsquareLocations: FileParser<import("../generated/mapsquare_locations").mapsquare_locations>;
    mapsquareEnvironment: FileParser<import("../generated/mapsquare_envs").mapsquare_envs>;
    mapZones: FileParser<import("../generated/mapzones").mapzones>;
    enums: FileParser<import("../generated/enums").enums>;
    fontmetrics: FileParser<import("../generated/fontmetrics").fontmetrics>;
    mapscenes: FileParser<import("../generated/mapscenes").mapscenes>;
    sequences: FileParser<import("../generated/sequences").sequences>;
    framemaps: FileParser<import("../generated/framemaps").framemaps>;
    frames: FileParser<import("../generated/frames").frames>;
    animgroupConfigs: FileParser<import("../generated/animgroupconfigs").animgroupconfigs>;
    models: FileParser<import("../generated/models").models>;
    oldmodels: FileParser<import("../generated/oldmodels").oldmodels>;
    classicmodels: FileParser<import("../generated/classicmodels").classicmodels>;
    spotAnims: FileParser<import("../generated/spotanims").spotanims>;
    rootCacheIndex: FileParser<import("../generated/rootcacheindex").rootcacheindex>;
    skeletalAnim: FileParser<import("../generated/skeletalanim").skeletalanim>;
    materials: FileParser<import("../generated/materials").materials>;
    oldmaterials: FileParser<import("../generated/oldmaterials").oldmaterials>;
    quickchatCategories: FileParser<import("../generated/quickchatcategories").quickchatcategories>;
    quickchatLines: FileParser<import("../generated/quickchatlines").quickchatlines>;
    environments: FileParser<import("../generated/environments").environments>;
    avatars: FileParser<import("../generated/avatars").avatars>;
    avatarOverrides: FileParser<import("../generated/avataroverrides").avataroverrides>;
    identitykit: FileParser<import("../generated/identitykit").identitykit>;
    structs: FileParser<import("../generated/structs").structs>;
    params: FileParser<import("../generated/params").params>;
    particles_0: FileParser<import("../generated/particles_0").particles_0>;
    particles_1: FileParser<import("../generated/particles_1").particles_1>;
    audio: FileParser<import("../generated/audio").audio>;
    proctexture: FileParser<import("../generated/proctexture").proctexture>;
    oldproctexture: FileParser<import("../generated/oldproctexture").oldproctexture>;
    maplabels: FileParser<import("../generated/maplabels").maplabels>;
    cutscenes: FileParser<import("../generated/cutscenes").cutscenes>;
    clientscript: FileParser<import("../generated/clientscript").clientscript>;
    clientscriptdata: FileParser<import("../generated/clientscriptdata").clientscriptdata>;
    interfaces: FileParser<import("../generated/interfaces").interfaces>;
    dbtables: FileParser<import("../generated/dbtables").dbtables>;
    dbrows: FileParser<import("../generated/dbrows").dbrows>;
};
